<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="0" total="2" passed="1" failed="1" skipped="0">
  <reporter-output>
  </reporter-output>
  <suite started-at="2022-11-26T08:57:19 IST" name="Suite" finished-at="2022-11-26T08:57:32 IST" duration-ms="12284">
    <groups>
    </groups>
    <test started-at="2022-11-26T08:57:19 IST" name="Test" finished-at="2022-11-26T08:57:32 IST" duration-ms="12284">
      <class name="testlayer.LoginTest">
        <test-method is-config="true" signature="initsetup()[pri:0, instance:testlayer.LoginTest@5f9b2141]" started-at="2022-11-26T08:57:19 IST" name="initsetup" finished-at="2022-11-26T08:57:26 IST" duration-ms="6546" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- initsetup -->
        <test-method signature="Login()[pri:0, instance:testlayer.LoginTest@5f9b2141]" started-at="2022-11-26T08:57:26 IST" name="Login" finished-at="2022-11-26T08:57:27 IST" duration-ms="828" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- Login -->
        <test-method is-config="true" signature="AfterMethod()[pri:0, instance:testlayer.LoginTest@5f9b2141]" started-at="2022-11-26T08:57:27 IST" name="AfterMethod" finished-at="2022-11-26T08:57:27 IST" duration-ms="172" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- AfterMethod -->
        <test-method is-config="true" signature="initsetup()[pri:0, instance:testlayer.LoginTest@5f9b2141]" started-at="2022-11-26T08:57:27 IST" name="initsetup" finished-at="2022-11-26T08:57:32 IST" duration-ms="4536" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- initsetup -->
        <test-method signature="gettitle()[pri:0, instance:testlayer.LoginTest@5f9b2141]" started-at="2022-11-26T08:57:32 IST" name="gettitle" finished-at="2022-11-26T08:57:32 IST" duration-ms="41" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [url] but found [http://demo.sentrifugo.com/index.php/]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [url] but found [http://demo.sentrifugo.com/index.php/]
at org.testng.Assert.fail(Assert.java:97)
at org.testng.Assert.assertEqualsImpl(Assert.java:136)
at org.testng.Assert.assertEquals(Assert.java:118)
at org.testng.Assert.assertEquals(Assert.java:575)
at org.testng.Assert.assertEquals(Assert.java:585)
at testlayer.LoginTest.gettitle(LoginTest.java:35)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:134)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:597)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:816)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:766)
at org.testng.TestRunner.run(TestRunner.java:587)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:384)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:378)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:337)
at org.testng.SuiteRunner.run(SuiteRunner.java:286)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1187)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1109)
at org.testng.TestNG.runSuites(TestNG.java:1039)
at org.testng.TestNG.run(TestNG.java:1007)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- gettitle -->
        <test-method is-config="true" signature="AfterMethod()[pri:0, instance:testlayer.LoginTest@5f9b2141]" started-at="2022-11-26T08:57:32 IST" name="AfterMethod" finished-at="2022-11-26T08:57:32 IST" duration-ms="93" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- AfterMethod -->
      </class> <!-- testlayer.LoginTest -->
    </test> <!-- Test -->
  </suite> <!-- Suite -->
</testng-results>
